FROM ubuntu:16.04

MAINTAINER Zhihao Yuan <zhihao.yuan@depaul.edu>

RUN apt-get update && apt-get install -y cmake && \
    apt-get clean

RUN apt-get update && apt-get install -y python-pip && \
    apt-get clean

RUN apt-get update && apt-get install -y git && \
    apt-get clean
